### ISSUE TITLE
The latest third and a half release has a corrupted FAT32 partition

### ISSUE THREAD

**Issue by toto99303** [christianhaitian/BittBoyV1#1]
Hello, excellent work on this, I really like the new boot screen, but unfortunatelly I have a problem. I downloaded this:

BB_V1_HWGhostFix_F32fix_BootLogo_042819.7z

And after I burn the image with Win32DiskImager or balena etcher it doesn't show up in my computer, so I can't copy any roms. It's working fine with the previous 8Gb image.
Let me know if you need more info on this.

**Comment by christianhaitian** [comment]
Thank you for the report.  I'll check it out.

**Comment by christianhaitian** [comment]
The fat32 partition is indeed unusable in Windows.  I've removed the release for now.
